==== Docker (Introduction)

Informations :

 Docker Hub Registry : disponibilitée d'images docker
                       images stocké du type username/reponitory

====== Afficher la liste des arguments possibles


docker
 
attach    Attach to a running container
build     Build a container from a Dockerfile
commit    Create a new image from a container's changes
diff      Inspect changes on a container's filesystem
export    Stream the contents of a container as a tar archive
history   Show the history of an image
images    List images
import    Create a new filesystem image from the contents of a tarball
info      Display system-wide information
insert    Insert a file in an image
inspect   Return low-level information on a container
kill      Kill a running container
login     Register or Login to the Docker registry server
logs      Fetch the logs of a container
port      Lookup the public-facing port which is NAT-ed to PRIVATE_PORT
ps        List containers
pull      Pull an image or a repository from the Docker registry server
push      Push an image or a repository to the Docker registry server
restart   Restart a running container
rm        Remove a container
rmi       Remove an image
run       Run a command in a new container
search    Search for an image in the Docker index
start     Start a stopped container
stop      Stop a running container
tag       Tag an image into a repository
version   Show the Docker version information
wait      Block until a container stops, then print its exit code

====== Afficher la version de docker

[source,bash]
----
docker version
----

====== Rechercher un container

[source,bash]
----
docker search tutorial
----

====== Afficher la liste des images disponibles

[source,bash]
----
docker images
----

====== Récupérer un container depuis le Docker Hub

[source,bash]
----
docker pull learn/tutorial
----

====== Exécuter une commande dans un conteneur

[source,bash]
----
docker run learn/tutorial echo 'hello world'
----

====== Afficher l'ID des conteneur suite changement

[source,bash]
----
docker ps -l
----

====== Commit un changement d'était d'une image

[source,bash]
----
docker commit 6982a9948422 learn/ping
effb66b31ebd
# => c'est l'id de la machine créé
----

====== Afficher les informations sur un container en run

[source,bash]
----
docker inspect eff
----

====== Pull une image sur le Hub

[source,bash]
----
docker push learn/ping
----

====== Entrer dans un container démarré

[source,bash]
----
docker exec -it <container_id> bash
----
