==== Securité Linux

Note : /!\ Documentation basée essentiellement sur du centos

====== Généralités

 > Protection physique : configuration BIOS
 > Installer uniquement les logiciels essentiels selon l'utilisation de la machine
   => Désactiver les services installés et inutiles
   => minimiser les logiciels pour minimiser le risque de failles
 > un service réseau par système ou machine virtuelle ou conteneur (docker)
 > séparer en partition disque /tmp, /home, /usr, /var/, /var/tmp + utilisation nosuid,noexec,nodev
 > Ne jamais laisser un logiciel avec la configuration par défaut, surtout si celui-ci
   est un service ouvert sur le net (ssh,nginx,apache,smtp,...)
 > Protéger les comptes utilisateurs
 > Protéger l'accès ssh efficacement
 > utiliser un firewall (configuration iptables avec table INPUT en DROP par défaut)
   En plus du firewall on peut utiliser les TCP Wrapper
   + fail2ban pour bloquer les tentatives de bruteforce
   + portsentry potentiellement pour bloquer les tentatives de scans
 > Installer un logiciel d'analyse de logs (logwatch par exemple)
 > Mettre à jour le système régulièrement
 > Monitorer les systèmes
 > Sauvegarder les systèmes et les données
 > configurer le service NTP
 > installer un IDS
 > mettre une banniere de connexion précisant qu'il est interdit de se connecter à la machine
   dans la conf ssh
 > Faire de la veille sur la sécurité (être au courant des dernières vulnérablités)
 > Faire preuve de bon sens


====== Logiciels de sécurité

 sysstat             : sar + iostat
 logwatch            : analyseur de log avec rapport journalier par mail
 fail2ban            : bloquer les tentatives de bruteforce notamment ssh !
 auditd              : audit
 aide                : Advenced Intrusion Detection Environment
 portsentry          : détection scan de ports
 chrootkit           : anti rootkit
 rkhunter            : anti rootkit
 snort               : Intrusion Detection System
 schred              : supprimer un fichier efficacement
 Apache/mod_security : module sécurité applicative pour Apache
 Apache/mod_evasive  : protection anti ddos Apache

====== Vérifications Basiques

[source,bash]
----
# >> vérifier les éxécutables setuid root 
find / -user root -perm /u+s
# >> vérifier les sockets réseau ouvertes
netstat -tulanp
# >> mettre à jour le système
# debian & debian like
apt-get update && apt-get upgrade
# RH / CentOS
yum update
# ArchLinux
pacman -Syu
# >> supprimer les logiciels inutiles
# lister les logiciels installés
# RH / CentOS
rpm -qa
----

====== Configuration ssh

 > Si accès ssh via internet, utiliser un port différent de 22
 > Clé DSA non recommandé
 > clé >= 2048 bits pour RSA
 > clé >= 256 bits pour ECDSA
 > les utilisateurs utilisants uniquemement le service sftp doivent
   être chrooté via l'option ChrootDirectory
 > Voir la fonction de la directive ForceCOmmand

[source]
----
# File /etc/ssh/sshd_config
ListenAdress 1.2.3.4:2222
Protocol 2
PermitRootLogin no
StrictModes yes
UserPrivilegeSeparation sandbox
PermitEmptyPasswords no
MaxAuthTries 2
LoginGraceTime 30
PrintLastLog yes
AllowUsers user1 user 2
AllowGroups group1 group2
PermitUserEnvironment no
AllowTcpForwarding no
X11Forwarding no
ForwardX11Trusted no
Banner /etc/ban
----

[source]
----
# File /etc/ssh/ssh_config
StrictHostKeyChecking ask
VerifyHostKeyDNS ask
----

====== Configuration fstab

[source]
----
/tmp     defaults,nosuid,noexec,nodev
/home    defaults,nosuid,nodev
/var     defaults,nosuid
/var/tmp defaults,nosuid,noexec,nodev
/boot    defaults,nosuid,noexec,nodev
/web     defaults,nosuid,nodev
/data    defaults,nosuid,noexec,nodev
----

Avec /boot en readonly (attention mise à jour noyau)

[source]
----
/boot    defaults,ro,nosuid,noexec,nodev
----

====== Protection Physique

Obliger l'utilisation du mot de passe root en mode single user

[source]
----
# file /etc/inittab
# require the root pw when booting into single user mode
~~:S:wait:/sbin/sulogin
# Don't allow any nut to kill the server
#ca::ctrlaltdel:/sbin/shutdown
# Autoriser les utilisateurs du fichier /etc/shutdown.allow
# de faire un ctrl+ alt + del avec l'option -a du shutdown
#ca::ctrlaltdel:/sbin/shutdown -a -t3 -r now
----

Désactiver l'USB si ce n'est pas utile (2 solutions)

[source,bash]
----
echo 'blacklist usb-storage' > /etc/modprobe.d/blacklist-usbstorage
----

[source]
----
# File /etc/modprobe.d/no-usb
install usb-storage /bin/true
----

====== Protection du HOMEDIR

[source,bash]
----
chmod 700 /root /home/*
# configurer un umask en 077 pour les utilisateurs
----

====== Password Policies

 configuration du fichier /etc/login.defs


Utiliser sha512 au lieu de md5

[source,bash]
----
authconfig --passalgo=sha512 --update
----

====== Restriction de cron et at

 configuration de :
 /etc/cron.deny
 /etc/at.deny

====== Sysctl 

[source]
----
net.ipv4.ip_forward = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.tcp_max_syn_backlog = 1280
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.all.secure_redirects = 0
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.accept_source_route = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.default.secure_redirects = 0
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.icmp_ignore_bogus_error_responses = 1
net.ipv4.tcp_syncookies = 1
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.tcp_timestamps = 0
----

====== TCP Wrappers

 Configuration des fichiers :
 /etc/hosts.deny
 /etc/hosts.allow

====== Iptables

 A configurer selon les besoins
 Par défaut configurer INPUT à DROP et autoriser les flux un par un
 FORWARD à DROP aussi si pas besoin

====== Fork Bomb

Mettre en place des limites notamment sur le nombre de processus pour éviter les fork bomb

[source,bash]
----
# fork bomb bash
:(){ :|:& };:
----

[source,ruby]
----
# fork bomb ruby
loop { fork }
----

[source,python]
----
# fork bomb python
import os

while True:
  os.fork()
----

[source]
----
# /etc/security/limits.conf
# > protection contre les fork bomb
*  hard  nproc  500
----

====== Désactiver IPV6 si inutile

[source]
----
# File /etc/sysconfig/network (CentOS)
NETWORKING_IPV6=no
IPV6INIT=no
----
