==== Processus Linux

====== Définitions
 
 fork   : copie conforme d'un processus existant, tous les attributs système du père 
          (par exemple les droits sur le système de fichier) sont transmis au fils, 
          de la même manière que l'héritage
          (source : wikipedia)
 thread : Un thread ou fil (d'exécution) ou tâche (terme et définition normalisés 
          par ISO/CEI 2382-7:2000 ; autres appellations connues : processus léger, 
          unité de traitement, unité d'exécution, fil d'instruction, processus allégé, 
          exétron1) est similaire à un processus car tous deux représentent l'exécution 
          d'un ensemble d'instructions du langage machine d'un processeur. Du point de 
          vue de l'utilisateur, ces exécutions semblent se dérouler en parallèle. 
          Toutefois, là où chaque processus possède sa propre mémoire virtuelle, 
          les threads d'un même processus se partagent sa mémoire virtuelle. 
          Par contre, tous les threads possèdent leur propre pile d’appel.
          (source : wikipedia)

Commandes utiles pour gérer les processus

 ps      : afficher l'état des processus en cours
 top     : afficher les tâches linux
 htop    : top amélioré
 pgrep   : recherche d'un processus suivant son nom ou d'autres élèments
 kill    : terminer un processus ou envoyer un signal
 pkill   : kill d'un processus suivant son nom ou d'autres élèments
 killall : kill un processus selon son nom
 nice    : modifier la priorité d'un processus
 renice  : modifier la priorité d'un processus
 vmstat  : afficher les statistiques de la mémoire virtuelle
 
====== Commandes ps

Définitions :

 > LWP  : un thread (Light-weight process)
 > NLWP : nombre de lwps (thread) d'un processus
 > PPID : Parent process ID
 > PID  : Process ID

ps par défaut n'affiche pas tous les processus.

[source,bash]
----
# Afficher tous les processus
ps -ef

# Afficher tous les processus (bsd style)
ps aux

# Afficher les processus par le nom ou le process id
ps -C apache2

# Afficher le processus par son id
ps -f -p 21435,21436


# Afficher tous les processus avec en première colone le nombre de thread
ps -e -o nlwp,pid,lwp,args

# Afficher les processus d'un utilisateur en particulier
ps -u root

# Afficher les 5 processus qui consomme le plus de CPU
ps aux --sort=pcpu|head -5

# Afficher les processus en arbre
ps -f --forest

# Afficher les processus fils d'un processus parent
ps -f --ppid 12219

# Afficher les threads d'un processus
ps -p 5335 -L
----

====== Commande vmstat

[source,bash]
----
# afficher le nombre de forks depuis le boot de la machine
vmstat -f

# l'info de la commande 'vmstat -f' est disponible dans /proc/stat
awk '/processes/ {print $2}' /proc/stat
----

====== Limites nproc

Les nproc permettent de limiter le nombre de processus par utilisateur.

Vérifier les limites nproc

[source,bash]
----
ulimit -u
----

Configuration des limites nproc au niveau du fichier /etc/security/limits.conf

[source]
----
orable soft nproc 2047
oracle prod nproc 16384
----

